// Generated by CoffeeScript 2.7.0
(function() {
  var board, list, math, num, squares;

  list = [1, 2, 3, 4, 5];

  math = {
    square: function(x) {
      return x * x;
    }
  };

  squares = (function() {
    var i, len, results;
    results = [];
    for (i = 0, len = list.length; i < len; i++) {
      num = list[i];
      results.push(math.square(num));
    }
    return results;
  })();

  console.log("Prints squares of [1,2,3,4,5]: \n\t\t   " + squares);

  board = document.getElementById("board");

  board.style.backgroundColor = "red";

}).call(this);
